version: "3"
services:
  postgres:
    image: postgres:10.5
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  rso-albumi:
    image: bostjan15/rsoalbumi:latest
    ports:
    - 8081:8081
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/postgres
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    depends_on:
    - postgres
  rso-slike:
    image: bostjan15/rsoslike:latest
    ports:
    - 8080:8080
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/postgres
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    depends_on:
    - postgres
  rso-uporabnik:
    image: bostjan15/rsouporabniki:latest
    ports:
    - 8082:8082
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/postgres
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    depends_on:
    - postgres
#  etcd:
#    image: quay.io/coreos/etcd:latest
#    ports:
#    - "2379:2379"
#    command: >-
#      /usr/local/bin/etcd
#      -name node1
#      -advertise-client-urls http://etcd:2379
#      -listen-client-urls http://0.0.0.0:2379
#      -initial-advertise-peer-urls http://etcd:2380
#      -listen-peer-urls http://0.0.0.0:2380
#      -initial-cluster node1=http://etcd:2380
#      -cors="*"